spring:
  application:
    name: logging-monitoring-service-1

logging:
  config: classpath:log4j2.yaml

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: logging-monitoring-service-1
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
