apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /app/logs/**/*.log
        Tag          app.*
        DB           /tmp/flb.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    
    [FILTER]
        Name   lua
        Match  *
        script /fluent-bit/etc/lua/convert_timestamp.lua
        call   convert

    [OUTPUT]
        Name         s3
        Match        app.*
        bucket       logging-monitoring-bucket 
        region       ap-south-1
        total_file_size 10M
        upload_timeout 2m
        use_put_object On
