apiVersion: v1
kind: Service
metadata:
  name: logging-monitoring
spec:
  selector:
    app: logging-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
