apiVersion: v1
kind: Service
metadata:
  name: logging-monitoring-service-1-service
spec:
  selector:
    app: logging-monitoring-service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
